---
apiVersion: v1
kind: Service
metadata:
  name: event-publisher-proxy
  namespace: system
  labels:
    control-plane: controller-manager
    app.kubernetes.io/name: service
    app.kubernetes.io/instance: event-publisher-proxy
    app.kubernetes.io/component: publisher-proxy
    app.kubernetes.io/created-by: eventing-manager
    app.kubernetes.io/part-of: eventing-manager
    app.kubernetes.io/managed-by: kustomize
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      name: http-client
---
# Source: publisher-proxy/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: publisher-proxy
  namespace: system
  labels:
    control-plane: controller-manager
    app.kubernetes.io/name: service
    app.kubernetes.io/instance: publisher-proxy
    app.kubernetes.io/component: publisher-proxy
    app.kubernetes.io/created-by: eventing-manager
    app.kubernetes.io/part-of: eventing-manager
    app.kubernetes.io/managed-by: kustomize
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      name: http-client
---
# Source: publisher-proxy/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: publisher-proxy-metrics
  namespace: system
  labels:
    control-plane: controller-manager
    app.kubernetes.io/name: service
    app.kubernetes.io/instance: publisher-proxy-metrics
    app.kubernetes.io/component: publisher-proxy
    app.kubernetes.io/created-by: eventing-manager
    app.kubernetes.io/part-of: eventing-manager
    app.kubernetes.io/managed-by: kustomize
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9090"
    prometheus.io/scheme: "http"
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9090
      name: http-metrics
---
# Source: publisher-proxy/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: publisher-proxy-health
  namespace: system
  labels:
    control-plane: controller-manager
    app.kubernetes.io/name: service
    app.kubernetes.io/instance: publisher-proxy-health
    app.kubernetes.io/component: publisher-proxy
    app.kubernetes.io/created-by: eventing-manager
    app.kubernetes.io/part-of: eventing-manager
    app.kubernetes.io/managed-by: kustomize
spec:
  type: ClusterIP
  ports:
    - name: http-status
      protocol: TCP
      port: 15020
      targetPort: 15020
