---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.19.0
  name: subscriptions.eventing.kyma-project.io
spec:
  group: eventing.kyma-project.io
  names:
    categories:
    - kyma-eventing
    kind: Subscription
    listKind: SubscriptionList
    plural: subscriptions
    singular: subscription
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .status.ready
      name: Ready
      type: string
    - jsonPath: .metadata.creationTimestamp
      name: Age
      type: date
    name: v1alpha2
    schema:
      openAPIV3Schema:
        description: Subscription is the Schema for the subscriptions API.
        properties:
          apiVersion:
            description: |-
              APIVersion defines the versioned schema of this representation of an object.
              Servers should convert recognized schemas to the latest internal value, and
              may reject unrecognized values.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
            type: string
          kind:
            description: |-
              Kind is a string value representing the REST resource this object represents.
              Servers may infer this from the endpoint the client submits requests to.
              Cannot be updated.
              In CamelCase.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
            type: string
          metadata:
            type: object
          spec:
            description: Defines the desired state of the Subscription.
            properties:
              config:
                additionalProperties:
                  type: string
                default:
                  maxInFlightMessages: "10"
                description: Map of configuration options that will be applied on
                  the backend.
                type: object
              id:
                description: Unique identifier of the Subscription, read-only.
                type: string
              sink:
                description: |-
                  Kubernetes Service that should be used as a target for the events that match the Subscription.
                  Must exist in the same Namespace as the Subscription.
                type: string
              source:
                description: Defines the origin of the event.
                type: string
              typeMatching:
                default: standard
                description: |-
                  Defines how types should be handled.<br />
                  - `standard`: backend-specific logic will be applied to the configured source and types.<br />
                  - `exact`: no further processing will be applied to the configured source and types.
                type: string
              types:
                description: List of event types that will be used for subscribing
                  on the backend.
                items:
                  type: string
                type: array
            required:
            - sink
            - source
            - types
            type: object
          status:
            description: SubscriptionStatus defines the observed state of Subscription.
            properties:
              backend:
                description: Backend-specific status which is applicable to the active
                  backend only.
                properties:
                  apiRuleName:
                    description: Name of the APIRule which is used by the Subscription.
                    type: string
                  emsSubscriptionStatus:
                    description: Status of the Subscription as reported by EventMesh.
                    properties:
                      lastFailedDelivery:
                        description: Timestamp of the last failed delivery.
                        type: string
                      lastFailedDeliveryReason:
                        description: Reason for the last failed delivery.
                        type: string
                      lastSuccessfulDelivery:
                        description: Timestamp of the last successful delivery.
                        type: string
                      status:
                        description: Status of the Subscription as reported by the
                          backend.
                        type: string
                      statusReason:
                        description: Reason for the current status.
                        type: string
                    type: object
                  emsTypes:
                    description: List of mappings from event type to EventMesh compatible
                      types. Used only with EventMesh as the backend.
                    items:
                      properties:
                        eventMeshType:
                          description: Event type that is used on the EventMesh backend.
                          type: string
                        originalType:
                          description: Event type that was originally used to subscribe.
                          type: string
                      required:
                      - eventMeshType
                      - originalType
                      type: object
                    type: array
                  emshash:
                    description: Hash used to identify an EventMesh Subscription retrieved
                      from the server without the WebhookAuth config.
                    format: int64
                    type: integer
                  ev2hash:
                    description: Checksum for the Subscription custom resource.
                    format: int64
                    type: integer
                  eventMeshLocalHash:
                    description: Hash used to identify an EventMesh Subscription posted
                      to the server without the WebhookAuth config.
                    format: int64
                    type: integer
                  externalSink:
                    description: Webhook URL used by EventMesh to trigger subscribers.
                    type: string
                  failedActivation:
                    description: Provides the reason if a Subscription failed activation
                      in EventMesh.
                    type: string
                  types:
                    description: List of event type to consumer name mappings for
                      the NATS backend.
                    items:
                      properties:
                        consumerName:
                          description: Name of the JetStream consumer created for
                            the event type.
                          type: string
                        originalType:
                          description: Event type that was originally used to subscribe.
                          type: string
                      required:
                      - originalType
                      type: object
                    type: array
                  webhookAuthHash:
                    description: Hash used to identify the WebhookAuth of an EventMesh
                      Subscription existing on the server.
                    format: int64
                    type: integer
                type: object
              conditions:
                description: Current state of the Subscription.
                items:
                  properties:
                    lastTransitionTime:
                      description: Defines the date of the last condition status change.
                      format: date-time
                      type: string
                    message:
                      description: Provides more details about the condition status
                        change.
                      type: string
                    reason:
                      description: Defines the reason for the condition status change.
                      type: string
                    status:
                      description: Status of the condition. The value is either `True`,
                        `False`, or `Unknown`.
                      type: string
                    type:
                      description: Short description of the condition.
                      type: string
                  required:
                  - status
                  type: object
                type: array
              ready:
                description: Overall readiness of the Subscription.
                type: boolean
              types:
                description: List of event types after cleanup for use with the configured
                  backend.
                items:
                  properties:
                    cleanType:
                      description: Event type after it was cleaned up from backend
                        compatible characters.
                      type: string
                    originalType:
                      description: Event type as specified in the Subscription spec.
                      type: string
                  required:
                  - cleanType
                  - originalType
                  type: object
                type: array
            required:
            - ready
            - types
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
